AWSTemplateFormatVersion: '2010-09-09'
Description: 'Electric City Aquarium: Sharks Interactive - Frontend Infrastructure - S3 Buckets and IAM (Simplified)'

Parameters:
  ProjectName:
    Type: String
    Default: electric-city-sharks
    Description: Project name used for resource naming

Resources:
  # S3 buckets
  StagingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-frontend-staging"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3000

  ProductionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-frontend-prod"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3000

  StorybookBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-storybook"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3000

  # S3 bucket policies
  StagingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StagingBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub "${StagingBucket}/*"

  ProductionBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProductionBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub "${ProductionBucket}/*"

  StorybookBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StorybookBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub "${StorybookBucket}/*"

  # IAM user for GitHub actions
  GitHubActionsUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${ProjectName}-github-actions"
      Policies:
        - PolicyName: !Sub "${ProjectName}-deployment-policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${StagingBucket}/*"
                  - !Sub "${ProductionBucket}/*"
                  - !Sub "${StorybookBucket}/*"
                  - !Ref StagingBucket
                  - !Ref ProductionBucket
                  - !Ref StorybookBucket

  # access keys for GitHub actions
  GitHubActionsAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref GitHubActionsUser

Outputs:
  StagingBucketName:
    Description: Name of the staging S3 bucket
    Value: !Ref StagingBucket

  ProductionBucketName:
    Description: Name of the production S3 bucket
    Value: !Ref ProductionBucket

  StorybookBucketName:
    Description: Name of the storybook S3 bucket
    Value: !Ref StorybookBucket

  StagingWebsiteURL:
    Description: URL of the staging website
    Value: !GetAtt StagingBucket.WebsiteURL

  ProductionWebsiteURL:
    Description: URL of the production website
    Value: !GetAtt ProductionBucket.WebsiteURL

  StorybookWebsiteURL:
    Description: URL of the storybook website
    Value: !GetAtt StorybookBucket.WebsiteURL

  GitHubActionsAccessKeyId:
    Description: Access Key ID for GitHub Actions
    Value: !Ref GitHubActionsAccessKey

  GitHubActionsSecretAccessKey:
    Description: Secret Access Key for GitHub Actions
    Value: !GetAtt GitHubActionsAccessKey.SecretAccessKey 